loadstring(game:HttpGet('https://raw.githubusercontent.com/shakar60/Evade/refs/heads/main/Misc/Top%20Bar%20Buttons.lua'))()
loadstring(game:HttpGet('https://raw.githubusercontent.com/shakar60/Evade/refs/heads/main/Misc/Leaderboard%20Buttons.lua'))()
loadstring(game:HttpGet('https://raw.githubusercontent.com/shakar60/Evade/refs/heads/main/Misc/Reload%20And%20Front%20View.lua'))()
loadstring(game:HttpGet('https://raw.githubusercontent.com/shakar60/Evade/refs/heads/main/Misc/Zoom%20Button.lua'))()
loadstring(game:HttpGet('https://raw.githubusercontent.com/shakar60/Evade/refs/heads/main/Misc/TimerGUI%20No%20Repeat.lua'))()
loadstring(game:HttpGet('https://raw.githubusercontent.com/shakar60/Evade/refs/heads/main/Misc/VIP%20Macro%20Command.lua'))()
